-- MySQL Script generated by MySQL Workbench
-- Wed Oct  9 17:33:36 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema codewrit_toyota_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema codewrit_toyota_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `codewrit_toyota_db` DEFAULT CHARACTER SET utf8 ;
USE `codewrit_toyota_db` ;

-- -----------------------------------------------------
-- Table `codewrit_toyota_db`.`user_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codewrit_toyota_db`.`user_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `type_UNIQUE` (`type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codewrit_toyota_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codewrit_toyota_db`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` TEXT NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `user_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_user_type1_idx` (`user_type_id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  CONSTRAINT `fk_user_user_type1`
    FOREIGN KEY (`user_type_id`)
    REFERENCES `codewrit_toyota_db`.`user_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `codewrit_toyota_db`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codewrit_toyota_db`.`admin` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `employee_id` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `sex` VARCHAR(10) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `telephone` VARCHAR(12) NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_admin_user1_idx` (`user_id` ASC),
  UNIQUE INDEX `employee_id_UNIQUE` (`employee_id` ASC),
  CONSTRAINT `fk_admin_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `codewrit_toyota_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `codewrit_toyota_db`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codewrit_toyota_db`.`customer` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  `sex` VARCHAR(10) NOT NULL,
  `company` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `codewrit_toyota_db`.`vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codewrit_toyota_db`.`vehicle` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `reg_no` VARCHAR(45) NOT NULL,
  `chasis_no` TEXT NULL,
  `make_and_model` TEXT NOT NULL,
  `selling_dealer` VARCHAR(45) NULL,
  `milleage` VARCHAR(45) NULL,
  `customer_id` INT(11) NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_vehicle_customer1_idx` (`customer_id` ASC),
  CONSTRAINT `fk_vehicle_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `codewrit_toyota_db`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `codewrit_toyota_db`.`appointment_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codewrit_toyota_db`.`appointment_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codewrit_toyota_db`.`appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codewrit_toyota_db`.`appointment` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `due_date` DATE NOT NULL,
  `description_of_service` TEXT NOT NULL,
  `service_advisor_id` INT(11) NOT NULL,
  `vehicle_id` INT(11) NOT NULL,
  `appointment_status_id` INT NULL DEFAULT 1,
  `create_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` INT(11) NOT NULL,
  `from_time` TIME NULL,
  `to_time` TIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_appointment_planning_vehicle1_idx` (`vehicle_id` ASC),
  INDEX `fk_appointment_appointment_status1_idx` (`appointment_status_id` ASC),
  INDEX `fk_appointment_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_appointment_planning_vehicle1`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `codewrit_toyota_db`.`vehicle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_appointment_appointment_status1`
    FOREIGN KEY (`appointment_status_id`)
    REFERENCES `codewrit_toyota_db`.`appointment_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_appointment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `codewrit_toyota_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `codewrit_toyota_db`.`appointment_staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codewrit_toyota_db`.`appointment_staff` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `employee_id` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `sex` VARCHAR(10) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `telephone` VARCHAR(12) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `employee_id_UNIQUE` (`employee_id` ASC),
  INDEX `fk_appointment_staff_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_appointment_staff_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `codewrit_toyota_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `codewrit_toyota_db`.`technician`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codewrit_toyota_db`.`technician` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `employee_id` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `expertise` TEXT NOT NULL,
  `user_id` INT(11) NOT NULL,
  `sex` VARCHAR(10) NOT NULL,
  `telephone` VARCHAR(12) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `employee_id_UNIQUE` (`employee_id` ASC),
  INDEX `fk_technicain_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_technicain_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `codewrit_toyota_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `codewrit_toyota_db`.`stall`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codewrit_toyota_db`.`stall` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `stall_id` VARCHAR(12) NOT NULL,
  `category` VARCHAR(255) NOT NULL,
  `location` VARCHAR(255) NOT NULL,
  `technician_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `stall_id_UNIQUE` (`stall_id` ASC),
  INDEX `fk_stall_technicain1_idx` (`technician_id` ASC),
  CONSTRAINT `fk_stall_technicain1`
    FOREIGN KEY (`technician_id`)
    REFERENCES `codewrit_toyota_db`.`technician` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `codewrit_toyota_db`.`job_planner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codewrit_toyota_db`.`job_planner` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `employee_id` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `sex` VARCHAR(10) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `telephone` VARCHAR(12) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `employee_id_UNIQUE` (`employee_id` ASC),
  INDEX `fk_job_planner_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_job_planner_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `codewrit_toyota_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `codewrit_toyota_db`.`job_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codewrit_toyota_db`.`job_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `value_UNIQUE` (`value` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codewrit_toyota_db`.`job_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codewrit_toyota_db`.`job_card` (
  `id` INT(11) NOT NULL,
  `begin_time` DATETIME NOT NULL,
  `finish_time` DATETIME NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `stall_id` INT(11) NOT NULL,
  `technician_id` INT(11) NOT NULL,
  `job_planner_id` INT(11) NOT NULL,
  `appointment_id` INT(11) NOT NULL,
  `job_status_id` INT NOT NULL,
  `vehicle_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_job_card_stall1_idx` (`stall_id` ASC),
  INDEX `fk_job_card_technicain1_idx` (`technician_id` ASC),
  INDEX `fk_job_card_job_planner1_idx` (`job_planner_id` ASC),
  INDEX `fk_job_card_appointment_planning1_idx` (`appointment_id` ASC),
  INDEX `fk_job_card_job_status1_idx` (`job_status_id` ASC),
  INDEX `fk_job_card_vehicle1_idx` (`vehicle_id` ASC),
  CONSTRAINT `fk_job_card_stall1`
    FOREIGN KEY (`stall_id`)
    REFERENCES `codewrit_toyota_db`.`stall` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_job_card_technician1`
    FOREIGN KEY (`technician_id`)
    REFERENCES `codewrit_toyota_db`.`technician` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_job_card_job_planner1`
    FOREIGN KEY (`job_planner_id`)
    REFERENCES `codewrit_toyota_db`.`job_planner` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_job_card_appointment_planning1`
    FOREIGN KEY (`appointment_id`)
    REFERENCES `codewrit_toyota_db`.`appointment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_job_card_job_status1`
    FOREIGN KEY (`job_status_id`)
    REFERENCES `codewrit_toyota_db`.`job_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_job_card_vehicle1`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `codewrit_toyota_db`.`vehicle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `codewrit_toyota_db`.`receptionist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codewrit_toyota_db`.`receptionist` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `employee_id` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `sex` VARCHAR(10) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `telephone` VARCHAR(12) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `employee_id_UNIQUE` (`employee_id` ASC),
  INDEX `fk_receptionist_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_receptionist_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `codewrit_toyota_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `codewrit_toyota_db`.`service_advisor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codewrit_toyota_db`.`service_advisor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `employee_id` VARCHAR(45) NULL,
  `telephone` VARCHAR(10) NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_service_advisor_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_service_advisor_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `codewrit_toyota_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `codewrit_toyota_db` ;

-- -----------------------------------------------------
-- Placeholder table for view `codewrit_toyota_db`.`user_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codewrit_toyota_db`.`user_view` (`id` INT, `username` INT, `email` INT, `password` INT, `create_time` INT, `user_type_id` INT, `type` INT);

-- -----------------------------------------------------
-- Placeholder table for view `codewrit_toyota_db`.`appointment_staff_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codewrit_toyota_db`.`appointment_staff_view` (`id` INT, `employee_id` INT, `first_name` INT, `middle_name` INT, `last_name` INT, `sex` INT, `user_id` INT, `telephone` INT, `username` INT, `email` INT, `password` INT, `create_time` INT);

-- -----------------------------------------------------
-- Placeholder table for view `codewrit_toyota_db`.`job_planner_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codewrit_toyota_db`.`job_planner_view` (`id` INT, `employee_id` INT, `first_name` INT, `middle_name` INT, `last_name` INT, `sex` INT, `user_id` INT, `telephone` INT, `username` INT, `email` INT, `password` INT, `create_time` INT);

-- -----------------------------------------------------
-- Placeholder table for view `codewrit_toyota_db`.`admin_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codewrit_toyota_db`.`admin_view` (`id` INT, `employee_id` INT, `first_name` INT, `middle_name` INT, `last_name` INT, `sex` INT, `user_id` INT, `telephone` INT, `username` INT, `email` INT, `password` INT, `create_time` INT);

-- -----------------------------------------------------
-- Placeholder table for view `codewrit_toyota_db`.`technician_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codewrit_toyota_db`.`technician_view` (`id` INT, `employee_id` INT, `first_name` INT, `middle_name` INT, `last_name` INT, `expertise` INT, `user_id` INT, `sex` INT, `telephone` INT, `username` INT, `email` INT, `password` INT, `create_time` INT);

-- -----------------------------------------------------
-- Placeholder table for view `codewrit_toyota_db`.`receptionist_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codewrit_toyota_db`.`receptionist_view` (`id` INT, `employee_id` INT, `first_name` INT, `middle_name` INT, `last_name` INT, `sex` INT, `user_id` INT, `telephone` INT, `username` INT, `email` INT, `password` INT, `create_time` INT);

-- -----------------------------------------------------
-- Placeholder table for view `codewrit_toyota_db`.`appointment_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codewrit_toyota_db`.`appointment_view` (`id` INT, `due_date` INT, `description_of_service` INT, `service_advisor_id` INT, `vehicle_id` INT, `appointment_status_id` INT, `create_date` INT, `user_id` INT, `from_time` INT, `to_time` INT, `vehicle_reg_no` INT, `vehicle_chasis_no` INT, `vehicle_make_and_model` INT, `vehicle_selling_dealer` INT, `vehicle_milleage` INT, `appointment_status` INT);

-- -----------------------------------------------------
-- Placeholder table for view `codewrit_toyota_db`.`vehicle_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codewrit_toyota_db`.`vehicle_view` (`id` INT, `reg_no` INT, `chasis_no` INT, `make_and_model` INT, `selling_dealer` INT, `milleage` INT, `customer_id` INT, `create_time` INT, `customer_fist_name` INT, `customer_middle_name` INT, `customer_last_name` INT, `customer_telephone` INT, `customer_company` INT, `customer_email` INT);

-- -----------------------------------------------------
-- Placeholder table for view `codewrit_toyota_db`.`stall_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codewrit_toyota_db`.`stall_view` (`id` INT, `stall_id` INT, `category` INT, `location` INT, `technician_id` INT, `technician_employee_id` INT, `technician_first_name` INT, `technician_middle_name` INT, `technician_last_name` INT);

-- -----------------------------------------------------
-- Placeholder table for view `codewrit_toyota_db`.`job_card_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codewrit_toyota_db`.`job_card_view` (`id` INT, `begin_time` INT, `finish_time` INT, `create_time` INT, `stall_id` INT, `technician_id` INT, `job_planner_id` INT, `appointment_id` INT, `job_status_id` INT, `vehicle_id` INT, `vehicle_reg_no` INT, `vehicle_chasis_no` INT, `vehicle_make_and_model` INT, `vehicle_milleage` INT, `customer_first_name` INT, `customer_middle_name` INT, `customer_last_name` INT, `customer_telephone` INT, `customer_email` INT, `customer_company` INT, `technician_employee_id` INT, `technician_first_name` INT, `technicain_middle_name` INT, `technician_last_name` INT, `appointment_due_date` INT, `description_of_service` INT, `job_planner_employee_id` INT, `job_planner_fist_name` INT, `job_planner_middle_name` INT, `job_planner_last_name` INT, `job_status` INT);

-- -----------------------------------------------------
-- Placeholder table for view `codewrit_toyota_db`.`service_advisor_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codewrit_toyota_db`.`service_advisor_view` (`id` INT, `first_name` INT, `middle_name` INT, `last_name` INT, `employee_id` INT, `telephone` INT, `user_id` INT, `username` INT, `password` INT, `email` INT);

-- -----------------------------------------------------
-- View `codewrit_toyota_db`.`user_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codewrit_toyota_db`.`user_view`;
USE `codewrit_toyota_db`;
CREATE  OR REPLACE VIEW `user_view` AS SELECT user.*,user_type.type from user inner join user_type on user_type.id=user.user_type_id;

-- -----------------------------------------------------
-- View `codewrit_toyota_db`.`appointment_staff_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codewrit_toyota_db`.`appointment_staff_view`;
USE `codewrit_toyota_db`;
CREATE  OR REPLACE VIEW `appointment_staff_view` AS select appointment_staff.*,user.username,user.email,user.password,user.create_time from appointment_staff inner join user on user.id=appointment_staff.user_id;

-- -----------------------------------------------------
-- View `codewrit_toyota_db`.`job_planner_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codewrit_toyota_db`.`job_planner_view`;
USE `codewrit_toyota_db`;
CREATE  OR REPLACE VIEW `job_planner_view` AS select job_planner.*,user.username,user.email,user.password,user.create_time from job_planner inner join user on user.id=job_planner.user_id;

-- -----------------------------------------------------
-- View `codewrit_toyota_db`.`admin_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codewrit_toyota_db`.`admin_view`;
USE `codewrit_toyota_db`;
CREATE  OR REPLACE VIEW `admin_view` AS select admin.*,user.username,user.email,user.password,user.create_time from admin inner join user on user.id=admin.user_id;

-- -----------------------------------------------------
-- View `codewrit_toyota_db`.`technician_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codewrit_toyota_db`.`technician_view`;
USE `codewrit_toyota_db`;
CREATE  OR REPLACE VIEW `technician_view` AS select technician.*,user.username,user.email,user.password, user.create_time from technician inner join user on user.id=technician.user_id;

-- -----------------------------------------------------
-- View `codewrit_toyota_db`.`receptionist_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codewrit_toyota_db`.`receptionist_view`;
USE `codewrit_toyota_db`;
CREATE  OR REPLACE VIEW `receptionist_view` AS select receptionist.*,user.username,user.email,user.password,user.create_time from receptionist inner join user on user.id=receptionist.user_id;

-- -----------------------------------------------------
-- View `codewrit_toyota_db`.`appointment_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codewrit_toyota_db`.`appointment_view`;
USE `codewrit_toyota_db`;
CREATE  OR REPLACE VIEW `appointment_view` AS select appointment.*,vehicle.reg_no as vehicle_reg_no,
vehicle.chasis_no as vehicle_chasis_no,vehicle.make_and_model as vehicle_make_and_model,
vehicle.selling_dealer as vehicle_selling_dealer,vehicle.milleage as vehicle_milleage,
 appointment_status.value as appointment_status from appointment inner join vehicle 
 on vehicle.id=appointment.vehicle_id inner join appointment_status on 
appointment_status.id=appointment.appointment_status_id;

-- -----------------------------------------------------
-- View `codewrit_toyota_db`.`vehicle_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codewrit_toyota_db`.`vehicle_view`;
USE `codewrit_toyota_db`;
CREATE  OR REPLACE VIEW `vehicle_view` AS select vehicle.*, customer.first_name as customer_fist_name,
customer.middle_name as customer_middle_name, customer.last_name as customer_last_name,
customer.telephone as customer_telephone, customer.company as customer_company,customer.email
as customer_email from vehicle inner join customer on customer.id=vehicle.customer_id;

-- -----------------------------------------------------
-- View `codewrit_toyota_db`.`stall_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codewrit_toyota_db`.`stall_view`;
USE `codewrit_toyota_db`;
CREATE  OR REPLACE VIEW `stall_view` AS select stall.*, technician.employee_id as technician_employee_id,
technician.first_name as technician_first_name,technician.middle_name as technician_middle_name,
technician.last_name as technician_last_name from stall inner join technician on technician.id=
stall.technician_id;

-- -----------------------------------------------------
-- View `codewrit_toyota_db`.`job_card_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codewrit_toyota_db`.`job_card_view`;
USE `codewrit_toyota_db`;
CREATE  OR REPLACE VIEW `job_card_view` AS select job_card.*,vehicle.reg_no as vehicle_reg_no,vehicle.chasis_no 
as vehicle_chasis_no, vehicle.make_and_model as vehicle_make_and_model,vehicle.milleage as vehicle_milleage,
customer.first_name as customer_first_name, customer.middle_name as customer_middle_name, customer.last_name
as customer_last_name, customer.telephone as customer_telephone, customer.email as customer_email, 
customer.company as customer_company, technician.employee_id as technician_employee_id,technician.first_name 
as technician_first_name,technician.middle_name as technicain_middle_name,
technician.last_name as technician_last_name,appointment.due_date as appointment_due_date,
appointment.description_of_service,job_planner.employee_id as job_planner_employee_id, 
job_planner.first_name as job_planner_fist_name, job_planner.middle_name as job_planner_middle_name,
job_planner.last_name as job_planner_last_name,job_status.value as job_status from job_card inner join
technician on technician.id = job_card.technician_id inner join appointment on appointment.id=
job_card.appointment_id inner join job_planner on job_planner.id=job_card.job_planner_id inner join 
job_status on job_status.id=job_status_id inner join vehicle on vehicle.id=job_card.vehicle_id 
inner join customer on customer.id=vehicle.customer_id;

-- -----------------------------------------------------
-- View `codewrit_toyota_db`.`service_advisor_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codewrit_toyota_db`.`service_advisor_view`;
USE `codewrit_toyota_db`;
CREATE  OR REPLACE VIEW `service_advisor_view` AS select service_advisor.*, user.username,user.password,user.email 
from service_advisor inner join user on user.id=service_advisor.user_id;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
